spring.data.mongodb.uri=mongodb+srv://username:Password@cluster0.jfbji.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=journaldb
spring.data.mongodb.auto-index-creation=true
#spring.data.mongodb.username=myjournaluser
#spring.data.mongodb.password=mypassword